### ISSUE TITLE
Issue with net=host containers

### ISSUE THREAD

**Issue by micw** [stuckyhm/prometheus-docker-sd#4]
If a scraped container uses net=host, the generated config does work. Even with `prometheus-scrape.ip_as_hostname` if fails since the IP is empty. A workaround ist to specify "172.17.0.1" (which is the docker0 interface address) works - maybe this should be used as IP in this case.

**Comment by stuckyhm** [comment]
Can you please check if issue #6 solves the problem too?

**Comment by micw** [comment]
Hello,
I think it's more complicated here. With the change, the hostname of the host is used which can resolve to anything, including the external (firewalled) IP address. That's better than before but works only by chance.
After re-thinking this, I'd say there is no "right" solution since it is not defined how a docker container can reach a service bound to the host network.
