### ISSUE TITLE
Option to set "prometheus-scrape.ip_as_hostname" as  global default

### ISSUE THREAD

**Issue by micw** [stuckyhm/prometheus-docker-sd#6]
On docker compose it seems that lookup by container name does not work (unless a "link" option is set). So I need to add "prometheus-scrape.ip_as_hostname=true" to all of my scraped containers. It would be very convenient to set this globally to true.

**Comment by stuckyhm** [comment]
There are some more problems with networking. I removed this option because it never works, if the container has more than one interface. Now the Container-Hostname is used as default. Please check if it work for you also.

**Comment by micw** [comment]
Works fine, thank you.
